version: v0.1
testId: "smoke-test-poc"
displayName: "Smoke Test POC"
testPlan: "jmeter/basic_smoke_test.jmx"
engineInstances: 1
env:
  - name: domain
    value: "www.google.com" # Ensures the test has a valid target
  - name: protocol
    value: "https"
failureCriteria:
  - avg(response_time_ms) > 5000
