version: v0.1
testId: smoke-test-poc
displayName: "Smoke Test POC"
testPlan: jmeter/basic_smoke_test.jmx
engineInstances: 1
configurationFiles: []
env:
  - name: domain
    value: "www.google.com" # The "Hello World" target
  - name: protocol
    value: "https"
  - name: path
    value: "/"
failureCriteria:
  - avg(response_time_ms) > 5000
